import type { NewsArticle } from "./types";

const publishedAt = "2026-08-23T18:10:00.000Z";

export const staticDocumentationArticles: NewsArticle[] = [
  {
    id: "docs-getting-started",
    title: "Getting Started with ESB Games",
    slug: "getting-started",
    subtitle: "A practical map of the ESB Games ecosystem and where to go next.",
    excerpt: "Understand the main ESB Games products, public information areas and the difference between platform, creator, support and safety resources.",
    body: [
      { type: "callout", tone: "info", title: "Pre-launch documentation", text: "ESB Games is still under active development. This guide explains the current public structure without implying that every product feature is already released." },
      { type: "heading", level: 2, text: "Start with the area you need" },
      { type: "list", items: [
        "ESB Games Platform — player accounts, discovery, communities and connected platform experiences.",
        "Creator Hub — public information about ESB Studio, creator tools and the creator ecosystem.",
        "Documentation — product and technical guidance that is safe to publish publicly.",
        "Help Centre — task-based self-service guidance for common questions.",
        "Support — private ticket conversations for issues that need an authorised staff member.",
        "Trust Centre — policies, safety guidance, privacy information and governance resources.",
        "Family Centre — linked-account and parental-control information for parents and guardians.",
      ] },
      { type: "heading", level: 2, text: "Check availability before relying on a feature" },
      { type: "paragraph", text: "Product pages may describe features that are released, testing or planned. Public download availability belongs on the Downloads page, service incidents belong on the Status site, and policy publication state belongs in the Trust Centre." },
      { type: "button", label: "Explore the Creator Hub", href: "/developer-hub", variant: "primary" },
      { type: "button", label: "Open the Help Centre", href: "/help", variant: "secondary" },
    ],
    author: "ESB Games",
    category: "Getting started",
    tags: ["documentation", "documentation-only", "getting-started"],
    publicationState: "Published",
    featured: true,
    indexable: true,
    sitemap: true,
    publishedAt,
    updatedAt: publishedAt,
    relatedSlugs: ["platform-overview", "esb-studio-overview", "publishing-status"],
    locale: "en",
    readingTime: 3,
  },
  {
    id: "docs-platform-overview",
    title: "ESB Games Platform Overview",
    slug: "platform-overview",
    subtitle: "How Discover, Belong and Build fit together across the platform.",
    excerpt: "A high-level overview of the player, social, creator, marketplace, events and family areas being brought together by ESB Games.",
    body: [
      { type: "heading", level: 2, text: "Discover" },
      { type: "paragraph", text: "The player side of ESB Games is designed around finding games, experiences, creators, events and other relevant activity. Discovery systems are part of the wider platform and may evolve while the product is tested." },
      { type: "heading", level: 2, text: "Belong" },
      { type: "paragraph", text: "Friends, groups, communities, messaging and events are intended to help people build lasting spaces around the things they enjoy. Social features are expected to use privacy, reporting and safety controls appropriate to the feature and audience." },
      { type: "heading", level: 2, text: "Build" },
      { type: "paragraph", text: "Creators use ESB Studio and connected creator tools to build experiences and content for the ecosystem. Creator publishing, Marketplace activity and monetisation have separate readiness, review and policy requirements." },
      { type: "heading", level: 2, text: "One account, multiple surfaces" },
      { type: "paragraph", text: "ESB Games is being designed as a connected ecosystem rather than a collection of unrelated websites. Player, creator, family, support and trust surfaces should use the appropriate account and permissions model for the task they perform." },
      { type: "callout", tone: "warning", title: "Availability varies", text: "A feature appearing in an overview does not mean it is publicly released. Use Downloads for client availability and the Status site for current service information." },
      { type: "button", label: "Explore ESB Games", href: "https://esbgames.com", variant: "primary" },
    ],
    author: "ESB Games",
    category: "Platform",
    tags: ["documentation", "documentation-only", "platform"],
    publicationState: "Published",
    featured: true,
    indexable: true,
    sitemap: true,
    publishedAt,
    updatedAt: publishedAt,
    relatedSlugs: ["getting-started", "esb-studio-overview", "publishing-status"],
    locale: "en",
    readingTime: 3,
  },
  {
    id: "docs-studio-overview",
    title: "ESB Studio Overview",
    slug: "esb-studio-overview",
    subtitle: "The creator environment being developed for building ESB Games experiences.",
    excerpt: "Understand the role of ESB Studio, project creation, scripting, testing and the current status of creator publishing.",
    body: [
      { type: "callout", tone: "info", title: "Development status", text: "ESB Studio is under active development. Interface, tooling and publishing requirements may change as testing continues." },
      { type: "heading", level: 2, text: "What ESB Studio is for" },
      { type: "paragraph", text: "ESB Studio is the creator environment for building games and interactive experiences for ESB Games. The product direction includes scene building, object and property editing, scripting, testing and connected creator workflows." },
      { type: "heading", level: 2, text: "Projects and collaboration" },
      { type: "paragraph", text: "Creator projects may be associated with individual creators or eligible organisations as the ownership and collaboration systems become available. Access and collaboration should follow explicit project permissions rather than simply sharing account credentials." },
      { type: "heading", level: 2, text: "Importing existing work" },
      { type: "paragraph", text: "ESB Games is developing workflows intended to reduce the effort required to bring compatible creator work into ESB Studio. Importing a project does not transfer licences for third-party code, music, images, brands or other assets; creators remain responsible for having the rights needed to use and publish imported material." },
      { type: "heading", level: 2, text: "Testing and publishing" },
      { type: "paragraph", text: "Local or private testing, review and public publishing can have different requirements. The public publishing workflow is still being validated, so creators should use the Publishing Status guide for the current documentation position." },
      { type: "button", label: "Open Creator Hub", href: "/developer-hub", variant: "primary" },
      { type: "button", label: "Read Scripting Overview", href: "/documentation/scripting-overview", variant: "secondary" },
    ],
    author: "ESB Games",
    category: "ESB Studio",
    tags: ["documentation", "documentation-only", "studio", "creators"],
    publicationState: "Published",
    featured: true,
    indexable: true,
    sitemap: true,
    publishedAt,
    updatedAt: publishedAt,
    relatedSlugs: ["scripting-overview", "publishing-status", "platform-overview"],
    locale: "en",
    readingTime: 4,
  },
  {
    id: "docs-scripting-overview",
    title: "Scripting Overview",
    slug: "scripting-overview",
    subtitle: "The current public direction for Lua scripting in ESB Studio.",
    excerpt: "An intentionally high-level overview of the Lua-based scripting direction while the runtime and public API surface are still being stabilised.",
    body: [
      { type: "callout", tone: "warning", title: "API reference not yet public", text: "This page does not invent classes, events or methods that have not been frozen for public use. Detailed API references and copy-paste examples will be added after the scripting runtime is stable enough to support them." },
      { type: "heading", level: 2, text: "Language direction" },
      { type: "paragraph", text: "ESB Studio scripting is being designed around Lua. The goal is to give creators a familiar, readable scripting language for game logic while ESB Games defines the platform-specific runtime, services and security boundaries." },
      { type: "heading", level: 2, text: "What creators should expect" },
      { type: "list", items: [
        "Scripts attached to appropriate project objects or runtime locations.",
        "A script editor and output/debugging workflow inside ESB Studio.",
        "Documented client/server or execution boundaries once those contracts are stable.",
        "Platform APIs that are versioned and documented before creators are expected to depend on them.",
        "Security restrictions that prevent scripts from bypassing platform permissions or accessing unauthorised data.",
      ] },
      { type: "heading", level: 2, text: "Why there are no fake examples here" },
      { type: "paragraph", text: "A code example becomes a compatibility promise very quickly. Until the actual runtime surface is stable, ESB Games would rather publish a smaller accurate guide than documentation for functions that may not exist in the shipped product." },
      { type: "button", label: "Read ESB Studio Overview", href: "/documentation/esb-studio-overview", variant: "secondary" },
    ],
    author: "ESB Games",
    category: "Scripting",
    tags: ["documentation", "documentation-only", "scripting", "lua"],
    publicationState: "Published",
    featured: false,
    indexable: true,
    sitemap: true,
    publishedAt,
    updatedAt: publishedAt,
    relatedSlugs: ["esb-studio-overview", "publishing-status"],
    locale: "en",
    readingTime: 3,
  },
  {
    id: "docs-publishing-status",
    title: "Publishing & Availability Status",
    slug: "publishing-status",
    subtitle: "How to interpret creator publishing, downloads and feature-readiness information during pre-launch development.",
    excerpt: "A source-of-truth guide for understanding what is public, testing or still planned across creator publishing and product availability.",
    body: [
      { type: "heading", level: 2, text: "Documentation status language" },
      { type: "table", headers: ["Label", "Meaning"], rows: [
        ["Available", "The feature is publicly available for the audience described."],
        ["Testing", "The feature exists but access or behaviour may be limited while it is validated."],
        ["In development", "The feature is actively being built and should not be treated as publicly available."],
        ["Planned", "The feature is part of the current product direction but implementation or timing is not guaranteed."],
      ] },
      { type: "heading", level: 2, text: "Creator publishing" },
      { type: "paragraph", text: "Public creator publishing workflows are still being validated. Review stages, eligibility, moderation checks, monetisation requirements and release controls may change before broad creator access." },
      { type: "heading", level: 2, text: "Downloads" },
      { type: "paragraph", text: "The Downloads page is the source of truth for whether ESB Games Player or ESB Studio installers are publicly available. A product screenshot or documentation page is not evidence that a downloadable build has been released." },
      { type: "heading", level: 2, text: "Service incidents" },
      { type: "paragraph", text: "Use the dedicated ESB Games Status site for current availability, maintenance and incident information. Documentation describes expected product behaviour; it is not a live status monitor." },
      { type: "button", label: "Check Downloads", href: "/download", variant: "primary" },
      { type: "button", label: "Open Service Status", href: "https://status.esbgames.com", variant: "secondary" },
    ],
    author: "ESB Games",
    category: "Publishing",
    tags: ["documentation", "documentation-only", "publishing", "availability"],
    publicationState: "Published",
    featured: false,
    indexable: true,
    sitemap: true,
    publishedAt,
    updatedAt: publishedAt,
    relatedSlugs: ["getting-started", "esb-studio-overview", "platform-overview"],
    locale: "en",
    readingTime: 3,
  },
];

export const staticDocumentationSlugs = new Set(staticDocumentationArticles.map((article) => article.slug));

export function getStaticDocumentationBySlug(slug: string) {
  return staticDocumentationArticles.find((article) => article.slug === slug) || null;
}

export function searchStaticDocumentation(query?: string) {
  const needle = query?.trim().toLowerCase();
  if (!needle) return staticDocumentationArticles;
  return staticDocumentationArticles.filter((article) => [article.title, article.subtitle || "", article.excerpt, article.category, ...article.tags].join(" ").toLowerCase().includes(needle));
}
