-- ESB Games About — newsletter subscription storage and server permissions
-- Safe to run more than once. This migration does not delete existing records.

create extension if not exists pgcrypto;

create table if not exists public.newsletter_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null unique,
  locale text not null default 'en',
  source text not null default 'about-homepage',
  status text not null default 'Subscribed',
  unsubscribe_token text,
  subscribed_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  updated_at timestamptz not null default now()
);


alter table public.newsletter_subscriptions
  add column if not exists unsubscribe_token text;

update public.newsletter_subscriptions
set unsubscribe_token = gen_random_uuid()::text
where unsubscribe_token is null or btrim(unsubscribe_token) = '';

create unique index if not exists newsletter_subscriptions_unsubscribe_token_idx
  on public.newsletter_subscriptions (unsubscribe_token)
  where unsubscribe_token is not null;

create index if not exists newsletter_subscriptions_status_idx
  on public.newsletter_subscriptions (status);
create index if not exists newsletter_subscriptions_subscribed_at_idx
  on public.newsletter_subscriptions (subscribed_at desc);

alter table public.newsletter_subscriptions enable row level security;

-- Newsletter writes are server-side only. Browser roles receive no direct table access.
revoke all on table public.newsletter_subscriptions from anon, authenticated;
grant usage on schema public to service_role;
grant select, insert, update on table public.newsletter_subscriptions to service_role;

-- Existing installs may use the identity sequence created by the bigint primary key.
do $$
declare
  seq_name text;
begin
  seq_name := pg_get_serial_sequence('public.newsletter_subscriptions', 'id');
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to service_role', seq_name);
  end if;
end $$;

-- Ask PostgREST to refresh its schema/privilege cache after the grant changes.
notify pgrst, 'reload schema';
