-- Run this in Supabase > SQL Editor.
-- The website writes through secure Next.js server routes using the service-role key.

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  ticket_id text not null unique,
  name text not null,
  email text not null,
  category text not null,
  subject text not null,
  message text not null,
  status text not null default 'Received',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_email_idx on public.support_tickets (email);
create index if not exists support_tickets_created_at_idx on public.support_tickets (created_at desc);

create table if not exists public.early_access (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  interest text not null,
  consent boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists early_access_email_idx on public.early_access (email);
create index if not exists early_access_created_at_idx on public.early_access (created_at desc);

alter table public.support_tickets enable row level security;
alter table public.early_access enable row level security;

-- No public insert/select policies are intentionally created.
-- The server-side service-role key bypasses RLS. Never expose that key to the browser.
