create extension if not exists pgcrypto;

-- Run this in Supabase > SQL Editor.
-- The website writes through secure Next.js server routes using the service-role key.

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  ticket_id text not null unique,
  name text not null,
  email text not null,
  category text not null,
  subject text not null,
  message text not null,
  status text not null default 'Received',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_email_idx on public.support_tickets (email);
create index if not exists support_tickets_created_at_idx on public.support_tickets (created_at desc);

create table if not exists public.early_access (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  interest text not null,
  consent boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists early_access_email_idx on public.early_access (email);
create index if not exists early_access_created_at_idx on public.early_access (created_at desc);

alter table public.support_tickets enable row level security;
alter table public.early_access enable row level security;

-- No public insert/select policies are intentionally created.
-- The server-side service-role key bypasses RLS. Never expose that key to the browser.

-- About website newsletter subscriptions
create table if not exists public.newsletter_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null unique,
  locale text not null default 'en',
  source text not null default 'about-homepage',
  status text not null default 'Subscribed',
  subscribed_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  updated_at timestamptz not null default now()
);
create index if not exists newsletter_subscriptions_status_idx on public.newsletter_subscriptions (status);
create index if not exists newsletter_subscriptions_subscribed_at_idx on public.newsletter_subscriptions (subscribed_at desc);
alter table public.newsletter_subscriptions enable row level security;

-- Backend-managed news and blog content. The body uses the safe block schema
-- implemented in lib/content/types.ts; arbitrary HTML is intentionally avoided.
create table if not exists public.cms_articles (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null,
  subtitle text,
  excerpt text not null,
  body jsonb not null default '[]'::jsonb,
  cover_image text,
  cover_image_alt text,
  cover_video text,
  author text not null default 'ESB Games Editorial',
  category text not null,
  tags text[] not null default '{}',
  publication_state text not null default 'Draft' check (publication_state in ('Draft','In Review','Awaiting Approval','Scheduled','Published','Archived','Unpublished','Failed')),
  featured boolean not null default false,
  seo_title text,
  seo_description text,
  social_image text,
  canonical_url text,
  published_at timestamptz,
  scheduled_for timestamptz,
  updated_at timestamptz not null default now(),
  related_slugs text[] not null default '{}',
  locale text not null default 'en',
  translation_group_id uuid,
  reading_time integer not null default 1,
  visibility text not null default 'Public',
  created_by uuid,
  approved_by uuid,
  created_at timestamptz not null default now(),
  unique (slug, locale)
);
create index if not exists cms_articles_publication_idx on public.cms_articles (publication_state, published_at desc);
create index if not exists cms_articles_category_idx on public.cms_articles (category);
create index if not exists cms_articles_locale_idx on public.cms_articles (locale);
create index if not exists cms_articles_tags_idx on public.cms_articles using gin (tags);
create index if not exists cms_articles_search_idx on public.cms_articles using gin (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(excerpt,'') || ' ' || coalesce(subtitle,'')));
alter table public.cms_articles enable row level security;

-- Backend-managed official product release records. A missing file_url is an
-- honest unavailable state and must never be presented as a completed download.
create table if not exists public.download_releases (
  id uuid primary key default gen_random_uuid(),
  product_slug text not null check (product_slug in ('play-platform','studio')),
  platform text not null check (platform in ('Windows','macOS','Linux','Web')),
  architecture text,
  version text,
  release_state text not null default 'Unavailable' check (release_state in ('Unavailable','Early Access','Beta','Stable','Paused')),
  file_url text,
  available boolean not null default false,
  release_date timestamptz,
  minimum_requirements text[] not null default '{}',
  release_notes_url text,
  checksum text,
  signed boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists download_releases_product_idx on public.download_releases (product_slug, platform, release_date desc);
alter table public.download_releases enable row level security;

-- Optional Backend-maintained documents can supplement the static search index.
create table if not exists public.site_search_documents (
  id uuid primary key default gen_random_uuid(),
  document_type text not null,
  title text not null,
  description text not null,
  route text not null,
  category text not null,
  locale text not null default 'en',
  keywords text[] not null default '{}',
  synonyms text[] not null default '{}',
  questions text[] not null default '{}',
  content text not null default '',
  priority integer not null default 50,
  published boolean not null default true,
  updated_at timestamptz not null default now()
);
create index if not exists site_search_documents_locale_idx on public.site_search_documents (locale, published);
create index if not exists site_search_documents_fts_idx on public.site_search_documents using gin (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description,'') || ' ' || coalesce(content,'')));
alter table public.site_search_documents enable row level security;

-- These tables are intentionally server-only. No public RLS policies are added.
-- The ESB Games Backend and Next.js server routes use the service-role key.
