create extension if not exists pgcrypto;

-- Optional backend schema for the ESB Games About website.
-- Review existing Production tables before running any statement.
-- Apply the integration migrations from the supplied package for News, Support and Careers.

-- About website newsletter subscriptions
create table if not exists public.newsletter_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null unique,
  locale text not null default 'en',
  source text not null default 'about-homepage',
  status text not null default 'Subscribed',
  unsubscribe_token text,
  subscribed_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.newsletter_subscriptions add column if not exists unsubscribe_token text;
update public.newsletter_subscriptions set unsubscribe_token = gen_random_uuid()::text where unsubscribe_token is null or btrim(unsubscribe_token) = '';
create unique index if not exists newsletter_subscriptions_unsubscribe_token_idx on public.newsletter_subscriptions (unsubscribe_token) where unsubscribe_token is not null;
create index if not exists newsletter_subscriptions_status_idx on public.newsletter_subscriptions (status);
create index if not exists newsletter_subscriptions_subscribed_at_idx on public.newsletter_subscriptions (subscribed_at desc);
alter table public.newsletter_subscriptions enable row level security;

-- News, Support and Careers are now connected through the ordered migrations
-- supplied in Supabase-Migrations. Do not create a separate cms_articles table
-- from this optional file; the integrated system creates a public-safe view over
-- the Backend content_records table.

-- Backend-managed official product release records. A missing file_url is an
-- honest unavailable state and must never be presented as a completed download.
create table if not exists public.download_releases (
  id uuid primary key default gen_random_uuid(),
  product_slug text not null check (product_slug in ('play-platform','studio')),
  platform text not null check (platform in ('Windows','macOS','Linux','Web')),
  architecture text,
  version text,
  release_state text not null default 'Unavailable' check (release_state in ('Unavailable','Preview','Beta','Stable','Paused')),
  file_url text,
  available boolean not null default false,
  release_date timestamptz,
  minimum_requirements text[] not null default '{}',
  release_notes_url text,
  checksum text,
  signed boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists download_releases_product_idx on public.download_releases (product_slug, platform, release_date desc);
alter table public.download_releases enable row level security;

-- Optional Backend-maintained documents can supplement the static search index.
create table if not exists public.site_search_documents (
  id uuid primary key default gen_random_uuid(),
  document_type text not null,
  title text not null,
  description text not null,
  route text not null,
  category text not null,
  locale text not null default 'en',
  keywords text[] not null default '{}',
  synonyms text[] not null default '{}',
  questions text[] not null default '{}',
  content text not null default '',
  priority integer not null default 50,
  published boolean not null default true,
  updated_at timestamptz not null default now()
);
create index if not exists site_search_documents_locale_idx on public.site_search_documents (locale, published);
create index if not exists site_search_documents_fts_idx on public.site_search_documents using gin (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description,'') || ' ' || coalesce(content,'')));
alter table public.site_search_documents enable row level security;

-- These tables are intentionally server-only. No public RLS policies are added.
-- The ESB Games Backend and Next.js server routes use the service-role key.
-- Add support and careers schemas only when their backend workflows are approved.
