import type { SearchDocument } from "@/lib/content/types";
import { supportArticles } from "@/lib/content/support";

const coreSearchDocuments: SearchDocument[] = [
  {
    id: "home",
    type: "Page",
    title: "ESB Games home",
    description: "Discover the ESB Games ecosystem being built around discovery, belonging and creation.",
    route: "/",
    category: "Platform",
    locale: "en",
    keywords: ["home", "ESB Games", "play", "games", "community", "platform"],
    synonyms: ["homepage", "main page", "gaming universe"],
    questions: ["What is ESB Games?", "Where can I play ESB Games?"],
    content: "Discover ESB Games, Creator Hub, Family Centre, trust and safety information, support and pre-launch product availability.",
    priority: 100,
  },
  {
    id: "about",
    type: "Page",
    title: "About ESB Games",
    description: "Learn about the ESB Games mission, principles and connected platform vision.",
    route: "/about",
    category: "Company",
    locale: "en",
    keywords: ["about", "mission", "principles", "company", "vision", "values"],
    synonyms: ["who are ESB Games", "company information", "our story"],
    questions: ["What does ESB Games do?", "What are ESB Games values?"],
    content: "Our mission, platform principles, safety, creativity, trust and global ambitions.",
    priority: 90,
  },
  {
    id: "creator-hub",
    type: "Creator",
    title: "Creator Hub",
    description: "Explore ESB Studio and the creator resources, publishing and growth systems being developed for ESB Games.",
    route: "/developer-hub",
    category: "Creators",
    locale: "en",
    keywords: ["creator hub", "developer hub", "ESB Studio", "create games", "publish", "developer tools"],
    synonyms: ["creator portal", "game development", "build a game", "studio download"],
    questions: ["How do I create a game?", "Where can I download ESB Studio?"],
    content: "Creator resources, documentation, studio tools, publishing, templates, APIs and creator support.",
    priority: 95,
  },
  {
    id: "parental-controls",
    type: "Help",
    title: "Family Centre",
    description: "Explore the screen-time, spending, communication, privacy and child-account controls being developed for Family Centre.",
    route: "/parental-controls",
    category: "Families",
    locale: "en",
    keywords: ["parental controls", "family centre", "child account", "screen time", "spending", "privacy"],
    synonyms: ["my child's account", "parent account", "family safety", "bedtime limits"],
    questions: ["How do I manage my child's account?", "How do I limit screen time?", "How do I stop spending?"],
    content: "Family settings, activity reports, approvals, privacy, communication controls and content restrictions.",
    priority: 94,
  },
  {
    id: "news",
    type: "News",
    title: "News & Updates",
    description: "Read company announcements, platform updates, creator news and engineering articles.",
    route: "/news",
    category: "News",
    locale: "en",
    keywords: ["news", "blog", "updates", "announcements", "articles", "company updates"],
    synonyms: ["newsroom", "latest ESB Games news", "patch notes"],
    questions: ["What is new at ESB Games?", "Where are ESB Games announcements?"],
    content: "Company News, Platform Updates, Creator Updates, Product Updates, Safety and Trust, Community, Events, Engineering and Careers.",
    priority: 92,
  },
  {
    id: "careers",
    type: "Careers",
    title: "Careers at ESB Games",
    description: "Explore remote roles and opportunities across ESB Games departments.",
    route: "/careers",
    category: "Company",
    locale: "en",
    keywords: ["careers", "jobs", "vacancies", "open roles", "hiring", "remote work"],
    synonyms: ["work at ESB Games", "join the team", "employment"],
    questions: ["Is ESB Games hiring?", "How do I apply for a job?"],
    content: "Executive Leadership, Trust and Safety, Engineering, Product, Marketing and Operations roles.",
    priority: 88,
  },
  {
    id: "trust",
    type: "Page",
    title: "Trust, Safety & Legal",
    description: "Find ESB Games safety, family, privacy, creator and legal resources in one place.",
    route: "/trust",
    category: "Trust & Safety",
    locale: "en",
    keywords: ["trust", "safety", "legal", "privacy", "community standards", "parents", "security"],
    synonyms: ["trust centre", "safety centre", "policies", "legal centre"],
    questions: ["Where are ESB Games policies?", "How does ESB Games approach safety?"],
    content: "Trust, Safety & Legal Centre with policy and guidance resources, Safety Centre, Family Centre resources, privacy and support routes.",
    priority: 99,
  },
  {
    id: "help-centre",
    type: "Help",
    title: "ESB Games Help Centre",
    description: "Browse practical ESB Games help topics for Accounts, safety, payments, playing, Creator tools, Family Centre, privacy and technical support.",
    route: "/help",
    category: "Support",
    locale: "en",
    keywords: ["help centre", "browse articles", "account help", "payment help", "creator help", "family help", "service status"],
    synonyms: ["support articles", "help articles", "how can we help", "knowledge base"],
    questions: ["Where is the Help Centre?", "How do I browse support articles?", "Where can I find ESB Games help?"],
    content: "Account and Login, Safety and Reporting, Payments and ESBucks, Games and Playing, Creators and Studio, Marketplace, Family Centre, Privacy and Data, Accessibility and Service Status.",
    priority: 99,
  },
  {
    id: "support",
    type: "Support",
    title: "ESB Games Support",
    description: "Find help with accounts, billing, safety, creator tools and technical issues.",
    route: "/support",
    category: "Support",
    locale: "en",
    keywords: ["support", "help", "ticket", "report", "billing", "account issue", "refund"],
    synonyms: ["customer service", "contact support", "need help", "appeal a ban"],
    questions: ["How do I contact support?", "I forgot my password", "How do I request a refund?", "How do I report a player?"],
    content: "Account and access, billing and payments, creator support, safety guidance, technical help and secure support conversations.",
    priority: 98,
  },
  {
    id: "download",
    type: "Download",
    title: "Downloads",
    description: "Follow public download availability for ESB Games Player and ESB Studio as development progresses.",
    route: "/download",
    category: "Products",
    locale: "en",
    keywords: ["download", "download ESB Games", "ESB Studio download", "launcher", "install", "game client", "creator software"],
    synonyms: ["ESB Games Player download", "install ESB Games", "download Studio", "ESB Games launcher"],
    questions: ["How do I download ESB Games?", "Where can I install ESB Studio?"],
    content: "ESB Games Player and ESB Studio are in development. Public availability, requirements and verification information will be published on the Downloads page.",
    priority: 99,
  },
  {
    id: "login",
    type: "Help",
    title: "Log in to ESB Games",
    description: "Access the universal ESB Games account login page.",
    route: "https://esbgames.com/login",
    category: "Accounts",
    locale: "en",
    keywords: ["login", "log in", "sign in", "account", "forgot password", "password reset"],
    synonyms: ["returning user", "access my account"],
    questions: ["How do I log in?", "I forgot my password", "How do I access my account?"],
    content: "Use the main ESB Games account portal to log in or recover account access.",
    priority: 100,
  },
  {
    id: "signup",
    type: "Help",
    title: "Create an ESB Games account",
    description: "Join ESB Games through the universal account portal.",
    route: "https://esbgames.com/sign-up",
    category: "Accounts",
    locale: "en",
    keywords: ["create account", "sign up", "register", "join ESB Games", "new account"],
    synonyms: ["make an account", "account registration", "join now"],
    questions: ["How do I create an account?", "How do I join ESB Games?"],
    content: "Open the main ESB Games sign-up page to create an account.",
    priority: 100,
  },
  {
    id: "subscriptions",
    type: "Page",
    title: "ESB Games subscriptions",
    description: "View the planned ESB Games membership structure and current benefit information.",
    route: "/subscriptions",
    category: "Platform",
    locale: "en",
    keywords: ["subscriptions", "membership", "plans", "premium", "plus", "pro", "max"],
    synonyms: ["paid plan", "upgrade account"],
    questions: ["What subscriptions does ESB Games offer?"],
    content: "Pre-launch Member, Plus, Pro and Max membership structure. Pricing and benefits are not yet final.",
    priority: 80,
  },
];

export const staticSearchDocuments: SearchDocument[] = [
  ...coreSearchDocuments,
  ...supportArticles.map((article) => ({
    id: `support-${article.slug}`,
    type: "Help" as const,
    title: article.title,
    description: article.description,
    route: `/support/help/${article.slug}`,
    category: "Support",
    locale: "en",
    keywords: [article.title, article.slug.replaceAll("-", " "), "support help"],
    synonyms: article.sections.flatMap((section) => [section.heading]),
    questions: [],
    content: [article.intro, ...article.sections.flatMap((section) => [...section.body, ...(section.steps || [])])].join(" "),
    priority: 86,
  })),
];
