-- ESB Games — Support ticket creation runtime fix
-- Additive migration. Run after 20260804_006_support_submission_pipeline_fix.sql.
--
-- Why this is needed:
-- The v2 creator generated and hashed the private access token inside PostgreSQL
-- using pgcrypto functions. On Supabase, extensions can be installed outside the
-- public schema, while the function deliberately used a restricted search_path.
-- The readiness check did not execute those crypto calls, so health could report
-- ready while real ticket creation failed.
--
-- v3 receives only a SHA-256 token hash generated by the trusted About server.
-- The raw private token never enters the database and the RPC no longer depends
-- on pgcrypto function lookup at runtime.

begin;

grant usage on schema public to service_role;

create or replace function public.support_create_ticket_v3(
  p_requester_account_id uuid,
  p_requester_name text,
  p_requester_email text,
  p_category_id text,
  p_subject text,
  p_description text,
  p_access_token_hash text,
  p_requester_locale text default 'en-GB',
  p_requester_region text default null,
  p_source text default 'About Website'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_category public.support_categories%rowtype;
  v_ticket public.support_tickets%rowtype;
  v_sender_type text;
  v_requester_email text;
begin
  if nullif(trim(p_requester_name), '') is null then
    raise exception 'name required';
  end if;

  if char_length(trim(p_requester_name)) > 120 then
    raise exception 'valid name required';
  end if;

  if nullif(trim(p_subject), '') is null or char_length(trim(p_subject)) > 160 then
    raise exception 'valid subject required';
  end if;

  if nullif(trim(p_description), '') is null or char_length(trim(p_description)) > 20000 then
    raise exception 'valid description required';
  end if;

  if p_access_token_hash is null or lower(trim(p_access_token_hash)) !~ '^[0-9a-f]{64}$' then
    raise exception 'valid access token hash required';
  end if;

  v_requester_email := nullif(lower(trim(coalesce(p_requester_email, ''))), '');

  if p_requester_account_id is null and (
    v_requester_email is null
    or v_requester_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
  ) then
    raise exception 'valid email required';
  end if;

  select *
    into v_category
    from public.support_categories
   where category_id = p_category_id
     and active
   limit 1;

  if not found then
    raise exception 'invalid support category';
  end if;

  v_sender_type := case when p_requester_account_id is null then 'Guest' else 'Account' end;

  insert into public.support_tickets(
    access_token_hash,
    requester_account_id,
    requester_name,
    requester_email,
    requester_email_verified,
    requester_locale,
    requester_region,
    category_id,
    team,
    subject,
    description,
    status,
    priority,
    source,
    verified_at
  ) values (
    lower(trim(p_access_token_hash)),
    p_requester_account_id,
    trim(p_requester_name),
    v_requester_email,
    p_requester_account_id is not null,
    coalesce(nullif(trim(p_requester_locale), ''), 'en-GB'),
    nullif(trim(coalesce(p_requester_region, '')), ''),
    v_category.category_id,
    v_category.default_team,
    trim(p_subject),
    trim(p_description),
    case when p_requester_account_id is null then 'Pending Email Verification' else 'New' end,
    v_category.default_priority,
    coalesce(nullif(trim(p_source), ''), 'About Website'),
    case when p_requester_account_id is null then null else now() end
  ) returning * into v_ticket;

  insert into public.support_ticket_participants(
    ticket_id,
    participant_type,
    account_id,
    display_name,
    email
  ) values (
    v_ticket.id,
    v_sender_type,
    p_requester_account_id,
    trim(p_requester_name),
    v_requester_email
  );

  insert into public.support_ticket_messages(
    ticket_id,
    sender_type,
    sender_account_id,
    sender_name,
    body
  ) values (
    v_ticket.id,
    v_sender_type,
    p_requester_account_id,
    trim(p_requester_name),
    trim(p_description)
  );

  insert into public.support_ticket_status_history(
    ticket_id,
    previous_status,
    new_status,
    acting_account_id,
    reason
  ) values (
    v_ticket.id,
    null,
    v_ticket.status,
    p_requester_account_id,
    'Ticket created'
  );

  insert into public.support_ticket_events(
    ticket_id,
    event_type,
    actor_type,
    actor_id,
    metadata
  ) values (
    v_ticket.id,
    'ticket_created',
    v_sender_type,
    coalesce(p_requester_account_id::text, v_requester_email, v_ticket.id::text),
    jsonb_build_object(
      'source', coalesce(nullif(trim(p_source), ''), 'About Website'),
      'category', p_category_id,
      'pipelineVersion', 3
    )
  );

  return jsonb_build_object(
    'ticketId', v_ticket.id,
    'ticketReference', v_ticket.ticket_reference,
    'requesterEmail', v_ticket.requester_email::text,
    'requesterAccountId', v_ticket.requester_account_id,
    'status', v_ticket.status,
    'requiresEmailVerification', p_requester_account_id is null,
    'pipelineVersion', 3
  );
end;
$$;

revoke all on function public.support_create_ticket_v3(uuid,text,text,text,text,text,text,text,text,text)
  from public, anon, authenticated;
grant execute on function public.support_create_ticket_v3(uuid,text,text,text,text,text,text,text,text,text)
  to service_role;

-- Readiness check for the same v3 pipeline used by real submissions.
create or replace function public.support_submission_preflight_v3()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, storage
as $$
declare
  v_category_count integer;
  v_bucket_exists boolean;
  v_creator_exists boolean;
  v_reference_ready boolean;
  v_message_trigger_ready boolean;
begin
  select count(*)::integer
    into v_category_count
    from public.support_categories
   where active;

  select exists(
    select 1
      from storage.buckets
     where id = 'support-ticket-evidence'
       and public = false
  ) into v_bucket_exists;

  v_creator_exists := to_regprocedure(
    'public.support_create_ticket_v3(uuid,text,text,text,text,text,text,text,text,text)'
  ) is not null;

  v_reference_ready :=
    to_regclass('public.support_ticket_reference_seq') is not null
    and to_regprocedure('public.next_support_ticket_reference()') is not null;

  select exists(
    select 1
      from pg_trigger
     where tgname = 'support_message_after_insert_trigger'
       and not tgisinternal
  ) into v_message_trigger_ready;

  return jsonb_build_object(
    'ready',
      v_category_count > 0
      and to_regclass('public.support_tickets') is not null
      and to_regclass('public.support_ticket_participants') is not null
      and to_regclass('public.support_ticket_messages') is not null
      and to_regclass('public.support_ticket_status_history') is not null
      and to_regclass('public.support_ticket_events') is not null
      and to_regclass('public.support_rate_limits') is not null
      and to_regclass('public.support_notification_outbox') is not null
      and v_bucket_exists
      and v_creator_exists
      and v_reference_ready
      and v_message_trigger_ready,
    'pipelineVersion', 3,
    'categoryCount', v_category_count,
    'evidenceBucketReady', v_bucket_exists,
    'ticketCreatorReady', v_creator_exists,
    'referenceGeneratorReady', v_reference_ready,
    'messageTriggerReady', v_message_trigger_ready
  );
end;
$$;

revoke all on function public.support_submission_preflight_v3()
  from public, anon, authenticated;
grant execute on function public.support_submission_preflight_v3()
  to service_role;

-- Reconfirm the supporting privileges used by the trusted About server.
grant select on table public.support_categories to service_role;
grant select, insert, update, delete on table
  public.support_tickets,
  public.support_ticket_participants,
  public.support_ticket_messages,
  public.support_ticket_internal_notes,
  public.support_ticket_attachments,
  public.support_ticket_assignments,
  public.support_ticket_status_history,
  public.support_ticket_verification_codes,
  public.support_ticket_guest_sessions,
  public.support_ticket_events,
  public.support_saved_replies,
  public.support_notification_outbox,
  public.support_rate_limits,
  public.public_site_notification_outbox,
  public.public_api_rate_limits
  to service_role;

grant usage, select, update on sequence public.support_ticket_reference_seq to service_role;

notify pgrst, 'reload schema';

commit;

-- Verification output. Every boolean should be true.
select
  to_regprocedure('public.support_create_ticket_v3(uuid,text,text,text,text,text,text,text,text,text)') is not null as create_ticket_v3_exists,
  to_regprocedure('public.support_submission_preflight_v3()') is not null as preflight_v3_exists,
  has_function_privilege(
    'service_role',
    'public.support_create_ticket_v3(uuid,text,text,text,text,text,text,text,text,text)',
    'EXECUTE'
  ) as create_ticket_v3_execute,
  has_function_privilege(
    'service_role',
    'public.support_submission_preflight_v3()',
    'EXECUTE'
  ) as preflight_v3_execute,
  has_sequence_privilege(
    'service_role',
    'public.support_ticket_reference_seq',
    'USAGE'
  ) as reference_sequence_usage,
  exists(
    select 1
      from storage.buckets
     where id = 'support-ticket-evidence'
       and public = false
  ) as evidence_bucket_private;
